export default [
  { name: `Adrek Robotics`, country: 'US', activities: ['robotics', 'cybernetics'], },
  { name: `Aesculapius Incorporated`, country: 'GR', activities: ['medical equipment'], },
  { name: `All Food`, country: 'MX', activities: ['agri-food industry'], },
  { name: `American Express-World`, country: 'US', activities: ['bank'], },
  { name: `Arasaka`, country: 'JP', activities: ['corporate militias', 'weaponry', 'military vehicles', 'cybernetics'], },
  { name: `BMW - McDonnell Douglas`, country: 'DE', activities: ['cars', 'military vehicles', 'avs', 'aviation'], },
  { name: `Baskin Undercover Incorporated`, country: 'US', activities: ['detectives'], },
  { name: `Bell-Boeing`, country: 'US', activities: ['aviation', 'helicopters', 'avs'], },
  { name: `Bensen`, country: 'ES', activities: ['hovercrafts'], },
  { name: `BioMass Laboratories Group, GmbH`, country: 'DE', activities: ['electronic chips', 'cybernetics', 'virtual realities'], },
  { name: `Biotec`, country: 'CA', activities: ['electronic chips', 'nanotechnologies'], },
  { name: `Biotechnica`, country: 'IT', activities: ['genetic', 'microbiology', 'biochemistry', 'cybernetics'], },
  { name: `Bodycure`, country: 'EU', activities: ['body care'], },
  { name: `Bodyweight Life Preservation Systems`, country: 'US', activities: ['medical electronics', 'cybernetics'], },
  { name: `Brandt-Neumann`, country: 'FR', activities: ['robotics', 'household appliances'], },
  { name: `Brennan Cycles`, country: 'MX', activities: ['motorcycles'], },
  { name: `British Aerospace`, country: 'GB', activities: ['military equipment', 'aviation', 'cars', 'electronic'], },
  { name: `British Broadcasting Corporation`, country: 'GB', activities: ['medias'], },
  { name: `BudgetArms`, country: 'US', activities: ['weaponry'], },
  { name: `C-Team`, country: 'US', activities: ['corporate mercenaries'], },
  { name: `Carolli`, country: 'IT', activities: ['robotics'], },
  { name: `Colt-Mauser`, country: 'US', activities: ['weaponry'], },
  { name: `Consolidated Agriculture`, country: 'US', activities: ['agri-food industry'], },
  { name: `Constitutional Arms`, country: 'US', activities: ['weaponry'], },
  { name: `Continental Catering`, country: 'EU', activities: ['receptions', 'caterers'], },
  { name: `Cybermatrix`, country: 'US', activities: ['cybernetics', 'electronic'], },
  { name: `Cybernetic Intervention Service`, country: 'US', activities: ['capture of cyberpsychos'], },
  { name: `Cyphire`, country: 'FR', activities: ['cybernetics'], },
  { name: `Cytech`, country: 'US', activities: ['cybernetics'], },
  { name: `Daimler-Benz`, country: 'DE', activities: ['transport', 'weaponry'], },
  { name: `DataEdge`, country: 'US', activities: ['electronic chips'], },
  { name: `DataTel`, country: 'FR', activities: ['telecommunications', 'electronic'], },
  { name: `Digital Products International`, country: 'US', activities: ['electronic', 'audio'], },
  { name: `Direct Dataware`, country: 'MX', activities: ['electronic chips', 'softwares'], },
  { name: `Diverse Media Systems`, country: 'US', activities: ['medias'], },
  { name: `Drakon Worldwide Fund`, country: 'LU', activities: ['bank'], },
  { name: `Dynalar Technology`, country: 'US', activities: ['cybernetics', 'acpa'], },
  { name: `English Tourism Board`, country: 'GB', activities: ['tourism'], },
  { name: `Euro Business Machines Corporation`, country: 'DE', activities: ['information technology', 'electronic'], },
  { name: `Euro Flight`, country: 'EU', activities: ['intercontinental transport'], },
  { name: `Eurobank`, country: 'EU', activities: ['bank'], },
  { name: `European Space Agency`, country: 'EU', activities: ['aerospace'], },
  { name: `Executive Transportation Service`, country: 'US', activities: ['vehicle leasing'], },
  { name: `Fabbrica d'Armi Pietro Beretta`, country: 'IT', activities: ['weaponry'], },
  { name: `Federated Arms`, country: 'US', activities: ['weaponry'], },
  { name: `Ford-Mazda`, country: 'US', activities: ['cars'], },
  { name: `Fujiwara`, country: 'JP', activities: ['bank', 'assurance', 'security', 'financial investments'], },
  { name: `GMI`, country: 'US', activities: ['military vehicles'], },
  { name: `General Dynamics`, country: 'US', activities: ['aviation', 'avs'], },
  { name: `Gibson Battlegear`, country: 'US', activities: ['body armors'], },
  { name: `Glock`, country: 'AT', activities: ['weaponry'], },
  { name: `Goldstein-Floydd`, country: 'GB', activities: ['bank'], },
  { name: `Goncz-Taurus`, country: 'BR', activities: ['weaponry'], },
  { name: `Harley Davidson`, country: 'US', activities: ['motorcycles'], },
  { name: `Harris & Company`, country: 'EU', activities: ['luxury apartment rental'], },
  { name: `Heckler & Koch`, country: 'DE', activities: ['weaponry'], },
  { name: `Hilliard Corporation`, country: 'GB', activities: ['financial empire', 'a variety of companies'], },
  { name: `Hughes`, country: 'US', activities: ['weaponry'], },
  { name: `ICON America`, country: 'US', activities: ['clothes', 'fashion'], },
  { name: `Imperial Metropolitan Agriculture`, country: 'GB', activities: ['agri-food industry'], },
  { name: `InfoComp`, country: 'US', activities: ['investigations', 'corporate information'], },
  { name: `International Companion Network`, country: 'US', activities: ['rental of temporary staff'], },
  { name: `International Electric Corporation`, country: 'DE', activities: ['space facilities', 'raw materials'], },
  { name: `Israel Military Industries`, country: 'IL', activities: ['weaponry'], },
  { name: `Japanese Aerospace Bureau`, country: 'JP', activities: ['aerospace'], },
  { name: `Kendachi`, country: 'JP', activities: ['monomolecular products', 'orbital alloys', 'weaponry'], },
  { name: `Kenjiri Technologies`, country: 'JP', activities: ['information technology'], },
  { name: `Korolev IG`, country: 'OR', activities: ['space transport', 'information technology'], },
  { name: `Kundalini Roadworks`, country: 'JP', activities: ['motorcycles'], },
  { name: `Lazarus Military Operations Group`, country: 'US', activities: ['mercenary operations'], },
  { name: `Lifetime Escort Service`, country: 'US', activities: ['bodyguards', 'escort'], },
  { name: `Lockeed-Cessna`, country: 'US', activities: ['aviation'], },
  { name: `Malorian Arms`, country: 'US', activities: ['weaponry'], },
  { name: `Masetto Tech Clothing`, country: 'IT', activities: ['clothes', 'tools'], },
  { name: `Matsushima-Kiroshi`, country: 'JP', activities: ['optics', 'cybernetics'], },
  { name: `Medellin Associates IG`, country: 'OR', activities: ['transport', 'bank', 'financial investments'], },
  { name: `Medical Technologies`, country: 'US', activities: ['body bank', 'hospital care'], },
  { name: `Mercedes`, country: 'DE', activities: ['transport vehicles'], },
  { name: `Merrill, Asukaga & Finch`, country: 'US', activities: ['bank', 'financial investments'], },
  { name: `Messerschmitt`, country: 'DE', activities: ['military vehicles', 'transport vehicles'], },
  { name: `Mexican Metals`, country: 'MX', activities: ['weaponry', 'acpa'], },
  { name: `Microtech`, country: 'US', activities: ['information technology', 'virtual realities'], },
  { name: `Mikoyan-Gurevich`, country: 'RU', activities: ['aviation', 'space transport', 'information technology', 'optics', 'agriculture'], },
  { name: `Militech`, country: 'US', activities: ['corporate mercenaries', 'weaponry', 'military vehicles'], },
  { name: `Mitsubishi-Sugo`, country: 'JP', activities: ['helicopters', 'robotics', 'tanks', 'cars'], },
  { name: `Mitsuzuki`, country: 'JP', activities: ['motorcycles'], },
  { name: `Moore Technologies`, country: 'CH', activities: ['cybernetics'], },
  { name: `Mustang Arms`, country: 'US', activities: ['weaponry'], },
  { name: `Network News 54`, country: 'US', activities: ['medias'], },
  { name: `New American Motors`, country: 'US', activities: ['cars'], },
  { name: `Nikkon`, country: 'JP', activities: ['optics', 'photos', 'cameras'], },
  { name: `Nissan-Ford`, country: 'US', activities: ['vehicles'], },
  { name: `Nova Arms`, country: 'US', activities: ['weaponry'], },
  { name: `Ocean Technology & Energy Corporation`, country: 'US', activities: ['ocean technology'], },
  { name: `Orbital Air`, country: 'KE', activities: ['orbital transport', 'spatial maintenance'], },
  { name: `Orion`, country: 'US', activities: ['hostage releases', 'corporate extractions'], },
  { name: `Osmanian Source AG`, country: 'OR', activities: ['weaponry', 'aerospace'], },
  { name: `PanEurope`, country: 'EU', activities: ['military vehicles'], },
  { name: `Peak & Derrera`, country: 'US', activities: ['precious materials broker'], },
  { name: `Peterbilt`, country: 'US', activities: ['transport vehicles'], },
  { name: `Petrochem`, country: 'US', activities: ['chemistry', 'agriculture', 'fuels'], },
  { name: `Pink Blossom`, country: 'OR', activities: ['power generation'], },
  { name: `Pointsman Pharmaceuticals`, country: 'OR', activities: ['pharmacology', 'chemistry', 'agri-food industry', 'bank'], },
  { name: `Pursuit Security`, country: 'US', activities: ['weaponry', 'electronic security'], },
  { name: `REO Meatwagon`, country: 'US', activities: ['ambulance services'], },
  { name: `Raven Microcybernetics`, country: 'US', activities: ['cybernetics', 'electronic', 'optics', 'information technology'], },
  { name: `Replitech`, country: 'OR', activities: ['genetic', 'biotechnology'], },
  { name: `Revolution Genetics Incorporated`, country: 'AQ', activities: ['genetic', 'biotechnology'], },
  { name: `Royal Enfield`, country: 'GB', activities: ['weaponry', 'military vehicles'], },
  { name: `Russian Arms`, country: 'RU', activities: ['acpa', 'weaponry'], },
  { name: `Schuman-Stein`, country: 'DE', activities: ['vehicles', 'raw materials', 'cybernetics'], },
  { name: `Security Services Incorporated`, country: 'US', activities: ['real estate agency', 'home services'], },
  { name: `SegAtari`, country: 'JP', activities: ['video games', 'virtual realities', 'robotics', 'weaponry'], },
  { name: `Shirakawa Research Industries`, country: 'JP', activities: ['submarines'], },
  { name: `Sikorski`, country: 'RU', activities: ['helicopters'], },
  { name: `Soviet Rocket Corps`, country: 'RU', activities: ['space construction', 'space transport'], },
  { name: `Soviet World Oil Industries`, country: 'US', activities: ['power generation', 'fuels', 'mines', 'chemistry'], },
  { name: `Sphere Courier`, country: 'AC', activities: ['high security freight transport'], },
  { name: `Stein & Wasserman`, country: 'DE', activities: ['weaponry'], },
  { name: `Sternmeyer Waffenfabrik`, country: 'DE', activities: ['weaponry'], },
  { name: `Sukhoi`, country: 'RU', activities: ['air vehicles'], },
  { name: `Sumitomo`, country: 'JP', activities: ['bank'], },
  { name: `Sungan Industries`, country: 'KR', activities: ['weaponry', 'electronic', 'cybernetics'], },
  { name: `Takaya`, country: 'KR', activities: ['cars'], },
  { name: `Tanson Group`, country: 'KR', activities: ['weaponry', 'cars', 'electronic', 'household appliances'], },
  { name: `Techtronica`, country: 'US', activities: ['high-tech weaponry', 'robotics'], },
  { name: `Telectronics`, country: 'US', activities: ['electronic', 'electronic security'], },
  { name: `Tempel Pharmaceuticals IG`, country: 'OR', activities: ['pharmacology', 'chemistry', 'agri-food industry', 'bank'], },
  { name: `Terra Nova`, country: 'OR', activities: ['environmental technology', 'space construction'], },
  { name: `Towa Manufacturing`, country: 'JP', activities: ['weaponry'], },
  { name: `Toyota-Chevrolet`, country: 'US', activities: ['cars'], },
  { name: `Trauma Team International`, country: 'US', activities: ['ambulance services'], },
  { name: `Tritech`, country: 'US', activities: ['electronic', 'security'], },
  { name: `Tsunami Arms`, country: 'JP', activities: ['high-tech weaponry'], },
  { name: `Tupolev`, country: 'OR', activities: ['aerospace'], },
  { name: `United Express`, country: 'US', activities: ['courier service', 'deliveries'], },
  { name: `United Orbital Soviet`, country: 'OR', activities: ['politics'], },
  { name: `Uniware`, country: 'US', activities: ['clothes', 'fashion'], },
  { name: `Utopian Corporation`, country: 'OR', activities: ['pharmacology', 'nanotechnologies'], },
  { name: `West City Bank`, country: 'US', activities: ['bank'], },
  { name: `West Geschellshaft Bank`, country: 'DE', activities: ['bank'], },
  { name: `Williams Management Incorporated`, country: 'US', activities: ['real estate agency'], },
  { name: `World News Service`, country: 'GB', activities: ['news agency'], },
  { name: `WorldSat Communications`, country: 'FR', activities: ['telecommunications', 'satellites'], },
  { name: `Wyzard Technologies`, country: 'IT', activities: ['cybernetics', 'information technology'], },
  { name: `Xoma Corporation`, country: 'US', activities: ['pharmacology'], },
  { name: `Yakurichi-Ural`, country: 'JP', activities: ['industrial vehicles', 'military vehicles'], },
  { name: `Yamaha`, country: 'JP', activities: ['musical instruments', 'motorcycles', 'electronic'], },
  { name: `Yoyodyne`, country: 'OR', activities: ['weaponry', 'aerospace', 'metallurgy', 'plastic', 'information technology'], },
  { name: `Zetatech`, country: 'US', activities: ['information technology', 'cybernetics'], },
]
