import { Activity, from, to } from './activity'
describe('activity', () => {
  it('from', () => {
        expect(from(Activity.A_VARIETY_OF_COMPANIES)).toBe('a variety of companies')
        expect(from(Activity.ACPA)).toBe('acpa')
        expect(from(Activity.AEROSPACE)).toBe('aerospace')
        expect(from(Activity.AGRI_FOOD_INDUSTRY)).toBe('agri-food industry')
        expect(from(Activity.AGRICULTURE)).toBe('agriculture')
        expect(from(Activity.AIR_VEHICLES)).toBe('air vehicles')
        expect(from(Activity.AMBULANCE_SERVICES)).toBe('ambulance services')
        expect(from(Activity.ASSURANCE)).toBe('assurance')
        expect(from(Activity.AUDIO)).toBe('audio')
        expect(from(Activity.AVIATION)).toBe('aviation')
        expect(from(Activity.AVS)).toBe('avs')
        expect(from(Activity.BANK)).toBe('bank')
        expect(from(Activity.BIOCHEMISTRY)).toBe('biochemistry')
        expect(from(Activity.BIOTECHNOLOGY)).toBe('biotechnology')
        expect(from(Activity.BODY_ARMORS)).toBe('body armors')
        expect(from(Activity.BODY_BANK)).toBe('body bank')
        expect(from(Activity.BODY_CARE)).toBe('body care')
        expect(from(Activity.BODYGUARDS)).toBe('bodyguards')
        expect(from(Activity.CAMERAS)).toBe('cameras')
        expect(from(Activity.CAPTURE_OF_CYBERPSYCHOS)).toBe('capture of cyberpsychos')
        expect(from(Activity.CARS)).toBe('cars')
        expect(from(Activity.CATERERS)).toBe('caterers')
        expect(from(Activity.CHEMISTRY)).toBe('chemistry')
        expect(from(Activity.CLOTHES)).toBe('clothes')
        expect(from(Activity.CORPORATE_EXTRACTIONS)).toBe('corporate extractions')
        expect(from(Activity.CORPORATE_INFORMATION)).toBe('corporate information')
        expect(from(Activity.CORPORATE_MERCENARIES)).toBe('corporate mercenaries')
        expect(from(Activity.CORPORATE_MILITIAS)).toBe('corporate militias')
        expect(from(Activity.COURIER_SERVICE)).toBe('courier service')
        expect(from(Activity.CYBERNETICS)).toBe('cybernetics')
        expect(from(Activity.DELIVERIES)).toBe('deliveries')
        expect(from(Activity.DETECTIVES)).toBe('detectives')
        expect(from(Activity.ELECTRONIC)).toBe('electronic')
        expect(from(Activity.ELECTRONIC_CHIPS)).toBe('electronic chips')
        expect(from(Activity.ELECTRONIC_SECURITY)).toBe('electronic security')
        expect(from(Activity.ENVIRONMENTAL_TECHNOLOGY)).toBe('environmental technology')
        expect(from(Activity.ESCORT)).toBe('escort')
        expect(from(Activity.FASHION)).toBe('fashion')
        expect(from(Activity.FINANCIAL_EMPIRE)).toBe('financial empire')
        expect(from(Activity.FINANCIAL_INVESTMENTS)).toBe('financial investments')
        expect(from(Activity.FUELS)).toBe('fuels')
        expect(from(Activity.GENETIC)).toBe('genetic')
        expect(from(Activity.HELICOPTERS)).toBe('helicopters')
        expect(from(Activity.HIGH_SECURITY_FREIGHT_TRANSPORT)).toBe('high security freight transport')
        expect(from(Activity.HIGH_TECH_WEAPONRY)).toBe('high-tech weaponry')
        expect(from(Activity.HOME_SERVICES)).toBe('home services')
        expect(from(Activity.HOSPITAL_CARE)).toBe('hospital care')
        expect(from(Activity.HOSTAGE_RELEASES)).toBe('hostage releases')
        expect(from(Activity.HOUSEHOLD_APPLIANCES)).toBe('household appliances')
        expect(from(Activity.HOVERCRAFTS)).toBe('hovercrafts')
        expect(from(Activity.INDUSTRIAL_VEHICLES)).toBe('industrial vehicles')
        expect(from(Activity.INFORMATION_TECHNOLOGY)).toBe('information technology')
        expect(from(Activity.INTERCONTINENTAL_TRANSPORT)).toBe('intercontinental transport')
        expect(from(Activity.INVESTIGATIONS)).toBe('investigations')
        expect(from(Activity.LUXURY_APARTMENT_RENTAL)).toBe('luxury apartment rental')
        expect(from(Activity.MEDIAS)).toBe('medias')
        expect(from(Activity.MEDICAL_ELECTRONICS)).toBe('medical electronics')
        expect(from(Activity.MEDICAL_EQUIPMENT)).toBe('medical equipment')
        expect(from(Activity.MERCENARY_OPERATIONS)).toBe('mercenary operations')
        expect(from(Activity.METALLURGY)).toBe('metallurgy')
        expect(from(Activity.MICROBIOLOGY)).toBe('microbiology')
        expect(from(Activity.MILITARY_EQUIPMENT)).toBe('military equipment')
        expect(from(Activity.MILITARY_VEHICLES)).toBe('military vehicles')
        expect(from(Activity.MINES)).toBe('mines')
        expect(from(Activity.MONOMOLECULAR_PRODUCTS)).toBe('monomolecular products')
        expect(from(Activity.MOTORCYCLES)).toBe('motorcycles')
        expect(from(Activity.MUSICAL_INSTRUMENTS)).toBe('musical instruments')
        expect(from(Activity.NANOTECHNOLOGIES)).toBe('nanotechnologies')
        expect(from(Activity.NEWS_AGENCY)).toBe('news agency')
        expect(from(Activity.OCEAN_TECHNOLOGY)).toBe('ocean technology')
        expect(from(Activity.OPTICS)).toBe('optics')
        expect(from(Activity.ORBITAL_ALLOYS)).toBe('orbital alloys')
        expect(from(Activity.ORBITAL_TRANSPORT)).toBe('orbital transport')
        expect(from(Activity.PHARMACOLOGY)).toBe('pharmacology')
        expect(from(Activity.PHOTOS)).toBe('photos')
        expect(from(Activity.PLASTIC)).toBe('plastic')
        expect(from(Activity.POLITICS)).toBe('politics')
        expect(from(Activity.POWER_GENERATION)).toBe('power generation')
        expect(from(Activity.PRECIOUS_MATERIALS_BROKER)).toBe('precious materials broker')
        expect(from(Activity.RAW_MATERIALS)).toBe('raw materials')
        expect(from(Activity.REAL_ESTATE_AGENCY)).toBe('real estate agency')
        expect(from(Activity.RECEPTIONS)).toBe('receptions')
        expect(from(Activity.RENTAL_OF_TEMPORARY_STAFF)).toBe('rental of temporary staff')
        expect(from(Activity.ROBOTICS)).toBe('robotics')
        expect(from(Activity.SATELLITES)).toBe('satellites')
        expect(from(Activity.SECURITY)).toBe('security')
        expect(from(Activity.SOFTWARES)).toBe('softwares')
        expect(from(Activity.SPACE_CONSTRUCTION)).toBe('space construction')
        expect(from(Activity.SPACE_FACILITIES)).toBe('space facilities')
        expect(from(Activity.SPACE_TRANSPORT)).toBe('space transport')
        expect(from(Activity.SPATIAL_MAINTENANCE)).toBe('spatial maintenance')
        expect(from(Activity.SUBMARINES)).toBe('submarines')
        expect(from(Activity.TANKS)).toBe('tanks')
        expect(from(Activity.TELECOMMUNICATIONS)).toBe('telecommunications')
        expect(from(Activity.TOOLS)).toBe('tools')
        expect(from(Activity.TOURISM)).toBe('tourism')
        expect(from(Activity.TRANSPORT)).toBe('transport')
        expect(from(Activity.TRANSPORT_VEHICLES)).toBe('transport vehicles')
        expect(from(Activity.VEHICLE_LEASING)).toBe('vehicle leasing')
        expect(from(Activity.VEHICLES)).toBe('vehicles')
        expect(from(Activity.VIDEO_GAMES)).toBe('video games')
        expect(from(Activity.VIRTUAL_REALITIES)).toBe('virtual realities')
        expect(from(Activity.WEAPONRY)).toBe('weaponry')
      })
  it('to', () => {
        expect(to('a variety of companies')).toBe(Activity.A_VARIETY_OF_COMPANIES)
        expect(to('acpa')).toBe(Activity.ACPA)
        expect(to('aerospace')).toBe(Activity.AEROSPACE)
        expect(to('agri-food industry')).toBe(Activity.AGRI_FOOD_INDUSTRY)
        expect(to('agriculture')).toBe(Activity.AGRICULTURE)
        expect(to('air vehicles')).toBe(Activity.AIR_VEHICLES)
        expect(to('ambulance services')).toBe(Activity.AMBULANCE_SERVICES)
        expect(to('assurance')).toBe(Activity.ASSURANCE)
        expect(to('audio')).toBe(Activity.AUDIO)
        expect(to('aviation')).toBe(Activity.AVIATION)
        expect(to('avs')).toBe(Activity.AVS)
        expect(to('bank')).toBe(Activity.BANK)
        expect(to('biochemistry')).toBe(Activity.BIOCHEMISTRY)
        expect(to('biotechnology')).toBe(Activity.BIOTECHNOLOGY)
        expect(to('body armors')).toBe(Activity.BODY_ARMORS)
        expect(to('body bank')).toBe(Activity.BODY_BANK)
        expect(to('body care')).toBe(Activity.BODY_CARE)
        expect(to('bodyguards')).toBe(Activity.BODYGUARDS)
        expect(to('cameras')).toBe(Activity.CAMERAS)
        expect(to('capture of cyberpsychos')).toBe(Activity.CAPTURE_OF_CYBERPSYCHOS)
        expect(to('cars')).toBe(Activity.CARS)
        expect(to('caterers')).toBe(Activity.CATERERS)
        expect(to('chemistry')).toBe(Activity.CHEMISTRY)
        expect(to('clothes')).toBe(Activity.CLOTHES)
        expect(to('corporate extractions')).toBe(Activity.CORPORATE_EXTRACTIONS)
        expect(to('corporate information')).toBe(Activity.CORPORATE_INFORMATION)
        expect(to('corporate mercenaries')).toBe(Activity.CORPORATE_MERCENARIES)
        expect(to('corporate militias')).toBe(Activity.CORPORATE_MILITIAS)
        expect(to('courier service')).toBe(Activity.COURIER_SERVICE)
        expect(to('cybernetics')).toBe(Activity.CYBERNETICS)
        expect(to('deliveries')).toBe(Activity.DELIVERIES)
        expect(to('detectives')).toBe(Activity.DETECTIVES)
        expect(to('electronic')).toBe(Activity.ELECTRONIC)
        expect(to('electronic chips')).toBe(Activity.ELECTRONIC_CHIPS)
        expect(to('electronic security')).toBe(Activity.ELECTRONIC_SECURITY)
        expect(to('environmental technology')).toBe(Activity.ENVIRONMENTAL_TECHNOLOGY)
        expect(to('escort')).toBe(Activity.ESCORT)
        expect(to('fashion')).toBe(Activity.FASHION)
        expect(to('financial empire')).toBe(Activity.FINANCIAL_EMPIRE)
        expect(to('financial investments')).toBe(Activity.FINANCIAL_INVESTMENTS)
        expect(to('fuels')).toBe(Activity.FUELS)
        expect(to('genetic')).toBe(Activity.GENETIC)
        expect(to('helicopters')).toBe(Activity.HELICOPTERS)
        expect(to('high security freight transport')).toBe(Activity.HIGH_SECURITY_FREIGHT_TRANSPORT)
        expect(to('high-tech weaponry')).toBe(Activity.HIGH_TECH_WEAPONRY)
        expect(to('home services')).toBe(Activity.HOME_SERVICES)
        expect(to('hospital care')).toBe(Activity.HOSPITAL_CARE)
        expect(to('hostage releases')).toBe(Activity.HOSTAGE_RELEASES)
        expect(to('household appliances')).toBe(Activity.HOUSEHOLD_APPLIANCES)
        expect(to('hovercrafts')).toBe(Activity.HOVERCRAFTS)
        expect(to('industrial vehicles')).toBe(Activity.INDUSTRIAL_VEHICLES)
        expect(to('information technology')).toBe(Activity.INFORMATION_TECHNOLOGY)
        expect(to('intercontinental transport')).toBe(Activity.INTERCONTINENTAL_TRANSPORT)
        expect(to('investigations')).toBe(Activity.INVESTIGATIONS)
        expect(to('luxury apartment rental')).toBe(Activity.LUXURY_APARTMENT_RENTAL)
        expect(to('medias')).toBe(Activity.MEDIAS)
        expect(to('medical electronics')).toBe(Activity.MEDICAL_ELECTRONICS)
        expect(to('medical equipment')).toBe(Activity.MEDICAL_EQUIPMENT)
        expect(to('mercenary operations')).toBe(Activity.MERCENARY_OPERATIONS)
        expect(to('metallurgy')).toBe(Activity.METALLURGY)
        expect(to('microbiology')).toBe(Activity.MICROBIOLOGY)
        expect(to('military equipment')).toBe(Activity.MILITARY_EQUIPMENT)
        expect(to('military vehicles')).toBe(Activity.MILITARY_VEHICLES)
        expect(to('mines')).toBe(Activity.MINES)
        expect(to('monomolecular products')).toBe(Activity.MONOMOLECULAR_PRODUCTS)
        expect(to('motorcycles')).toBe(Activity.MOTORCYCLES)
        expect(to('musical instruments')).toBe(Activity.MUSICAL_INSTRUMENTS)
        expect(to('nanotechnologies')).toBe(Activity.NANOTECHNOLOGIES)
        expect(to('news agency')).toBe(Activity.NEWS_AGENCY)
        expect(to('ocean technology')).toBe(Activity.OCEAN_TECHNOLOGY)
        expect(to('optics')).toBe(Activity.OPTICS)
        expect(to('orbital alloys')).toBe(Activity.ORBITAL_ALLOYS)
        expect(to('orbital transport')).toBe(Activity.ORBITAL_TRANSPORT)
        expect(to('pharmacology')).toBe(Activity.PHARMACOLOGY)
        expect(to('photos')).toBe(Activity.PHOTOS)
        expect(to('plastic')).toBe(Activity.PLASTIC)
        expect(to('politics')).toBe(Activity.POLITICS)
        expect(to('power generation')).toBe(Activity.POWER_GENERATION)
        expect(to('precious materials broker')).toBe(Activity.PRECIOUS_MATERIALS_BROKER)
        expect(to('raw materials')).toBe(Activity.RAW_MATERIALS)
        expect(to('real estate agency')).toBe(Activity.REAL_ESTATE_AGENCY)
        expect(to('receptions')).toBe(Activity.RECEPTIONS)
        expect(to('rental of temporary staff')).toBe(Activity.RENTAL_OF_TEMPORARY_STAFF)
        expect(to('robotics')).toBe(Activity.ROBOTICS)
        expect(to('satellites')).toBe(Activity.SATELLITES)
        expect(to('security')).toBe(Activity.SECURITY)
        expect(to('softwares')).toBe(Activity.SOFTWARES)
        expect(to('space construction')).toBe(Activity.SPACE_CONSTRUCTION)
        expect(to('space facilities')).toBe(Activity.SPACE_FACILITIES)
        expect(to('space transport')).toBe(Activity.SPACE_TRANSPORT)
        expect(to('spatial maintenance')).toBe(Activity.SPATIAL_MAINTENANCE)
        expect(to('submarines')).toBe(Activity.SUBMARINES)
        expect(to('tanks')).toBe(Activity.TANKS)
        expect(to('telecommunications')).toBe(Activity.TELECOMMUNICATIONS)
        expect(to('tools')).toBe(Activity.TOOLS)
        expect(to('tourism')).toBe(Activity.TOURISM)
        expect(to('transport')).toBe(Activity.TRANSPORT)
        expect(to('transport vehicles')).toBe(Activity.TRANSPORT_VEHICLES)
        expect(to('vehicle leasing')).toBe(Activity.VEHICLE_LEASING)
        expect(to('vehicles')).toBe(Activity.VEHICLES)
        expect(to('video games')).toBe(Activity.VIDEO_GAMES)
        expect(to('virtual realities')).toBe(Activity.VIRTUAL_REALITIES)
        expect(to('weaponry')).toBe(Activity.WEAPONRY)
        expect(to('unknown')).toBe(undefined)
  })
})
